name: landing_page
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  visibility_detector: ^0.4.0+2
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/team/ariel.jpg
    - assets/team/julieta.jpg
    - assets/team/mayte.jpg
    - assets/team/TELEFONO.png
    - assets/team/celular.png
    - assets/team/celular2.png
    - assets/team/celular3.png
    - assets/team/Mayteqr.png
    - assets/team/Julietaqr.png
    - assets/images/logo.png